### ISSUE TITLE
Использование звука с микрофона

### ISSUE THREAD

**Issue by volnov** [n3tman/GrinchPlayer#1]
Спасибо за шикарный софт, но у меня есть небольшая программа.

В отличии от классических технопранкеров, я использую свой голос на равне с записями бомбящих ребят.

Но так как в скайпе/любом софте для звонков только ОДИН аудиовход, и получается что нельзя юзать GrinchPlayer+микрофон.

Я предлагаю сделать ВХОД чтобы заводить микрофон в GrinchPlayer, и выводить уже общий микс звука из микро и воспроизводимых файлов. 

Ну и контроль громкости мика тоже было бы супер добавить.

Очень жду такой апдейт!

**Comment by n3tman** [comment]
Как обсудили в Discord, микширование аудиоисточников все-таки выходит за рамки плеера. Да и использованные технологии (Electron, JavaScript) ограничивают создание такого функционала в принципе.

Для этой задачи отлично подходят программные микшеры с виртуальными кабелями, например [Voicemeeter](https://www.vb-audio.com/Voicemeeter/).

То есть, выводим звук из плеера в один канал, в микшере ловим его на вход и соединяем с микрофонным. На выход (в колонки или в OBS на стрим) уже идет один объединенный поток.

Была идея заводить звук в плеер для визуализации (чтобы было ясно, где воспроизводятся звуки, а где говорит собеседник). Но и от этой идеи решено было отказаться, потому что все давно сделано в готовых утилитах, например [Spectralissime](https://www.vb-audio.com/Spectralissime/).

**Comment by superteremok** [comment]
> Спасибо за шикарный софт, но у меня есть небольшая программа.
> 
> В отличии от классических технопранкеров, я использую свой голос на равне с записями бомбящих ребят.
> 
> Но так как в скайпе/любом софте для звонков только ОДИН аудиовход, и получается что нельзя юзать GrinchPlayer+микрофон.
> 
> Я предлагаю сделать ВХОД чтобы заводить микрофон в GrinchPlayer, и выводить уже общий микс звука из микро и воспроизводимых файлов.
> 
> Ну и контроль громкости мика тоже было бы супер добавить.
> 
> Очень жду такой апдейт!

ахаха, много ли ты хочешь вольнов? ты ж пиздабол однако. я те писал по поводу эвакуации, а ты нихуя не мог ответить. значит кто? пиздабол правильно, слова не держишь.
