### ISSUE TITLE
Переименовывание карточек

### ISSUE THREAD

**Issue by volnov** [n3tman/GrinchPlayer#5]
Очень не хватает возможности менять название карточки звука.

**Comment by n3tman** [comment]
А вроде бы есть уже такое:
- в режиме редактирования, Ctrl+правый клик мышки

![grinch-rename](https://user-images.githubusercontent.com/16892631/82117571-8ebfe880-9779-11ea-9e72-f5f2a667330e.gif)

Единственное, нельзя переименовать карточки, которые еще в колоде. Сначала их нужно добавить на страницу. Но если потом удалить со страницы, в колоде будет новое название.

Также, название файла (.mp3) при этом остается прежним. Подразумевается, что файлы для страниц изначально названы правильно (или вообще пофиг на это).

Управление в разных режимах описано в **О программе** - **Помощь**.
